general:
  parameters:
    AvailabilityZones: us-east-1a, us-east-1c, us-east-1d, us-east-1e, us-east-1f
    ControlPlaneSecurityGroup: sg-0b11db94c5391376e
    EKSControlPlane: EKS-Q5myVk6FH90I
    HelmLambdaArn: arn:aws:lambda:us-east-1:394942936170:function:tCaT-tag-cloudbees-core-62d299d6-CloudB-HelmLambda-1UYKRIXFYPWBE
    InitialNodeGroupSecurityGroup: sg-035dd00ba23929614
    KeyPairName: cloudbees-core-quickstart
    KubeClusterName: EKS-Q5myVk6FH90I
    KubeConfigPath: s3://tcat-tag-cloudbees-core-62d299d6-kubeconfigbucket-1cpwwcpymgxpo/.kube/config.enc
    KubeGetLambdaArn: arn:aws:lambda:us-east-1:394942936170:function:tCaT-tag-cloudbees-core-62d299d6-Clo-KubeGetLambda-U2SVZ5D7BFO
    KubeManifestLambdaArn: arn:aws:lambda:us-east-1:394942936170:function:tCaT-tag-cloudbees-core-62d299d-KubeManifestLambda-J8JWVBP1G9UA
    NodeInstanceProfile: tCaT-tag-cloudbees-core-existing-vpc-51de07c0-EKSStack-1EDUISGEG2OM8-IamStack-150UVWWJMWDG6-NodeInstanceProfile-13KW3V4BJCBMW
    PrivateSubnet1ID: subnet-05344dadfb02cbeb2
    PrivateSubnet2ID: subnet-087927fa7e99d2a85
    PrivateSubnet3ID: subnet-0e9ceb7b632ddf178
    PublicSubnet1ID: subnet-00efbb20ce7696962
    PublicSubnet2ID: subnet-08b39e4e208760efc
    PublicSubnet3ID: subnet-08d8b3aed35d0501f
    RemoteAccessCIDR: 0.0.0.0/0
    VPCID: vpc-0f285dc8eec524b4d
