AWSTemplateFormatVersion: 2010-09-09
Description: Deploys CloudBees Core into an existing Kubernetes cluster (qs-1pipqrqje)

Parameters:
  KubeGetLambdaArn:
    Type: String
  HelmLambdaArn:
    Type: String
  ClusterName:
    Type: String
  StorageClassName:
    Type: String
  CustomValueYaml:
    Type: String

Resources:
  CloudBeesCore:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      ClusterName: !Ref ClusterName
      RepoUrl: https://charts.cloudbees.com/public/cloudbees
      Chart: cloudbees/cloudbees-core
      Version: 3.16.1+a3fdb4ae4e87
      Name: cloudbees-core
      Namespace: cloudbees-core
      ValueYaml: !Sub |
        nginx-ingress:
          Enabled: true
        OperationsCenter:
          Platform: eks
          ExtraConfigMaps:
          - name: cloudbees-referrer
            labels:
              app.kubernetes.io/component: trial-telemetry
            data:
              .cloudbees-referrer.txt: |
                Core on AWS Quick Start
          ExtraVolumes:
            - name: cloudbees-referrer
              configMap:
                name:  cloudbees-referrer
          ExtraVolumeMounts:
          - name: cloudbees-referrer
            mountPath: /var/jenkins_home/.cloudbees-referrer.txt
            subPath: .cloudbees-referrer.txt
            readOnly: true
        Persistence:
          StorageClass: ${StorageClassName}
      CustomValueYaml: !Ref CustomValueYaml
  IngressHostName:
    DependsOn: CloudBeesCore
    Type: "Custom::KubeGet"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref KubeGetLambdaArn
      ClusterName: !Ref ClusterName
      Namespace: cloudbees-core
      Name: 'svc/cloudbees-core-nginx-ingress-controller'
      JsonPath: '{.status.loadBalancer.ingress[0].hostname}'

Outputs:
  CloudBeesJenkinsOperationsCenterUrl:
    Value: !Sub "http://${IngressHostName}/cjoc"
